replicaCount: 1

image:
  repository: website
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env:
  NEXT_PUBLIC_SITE_URL: ""
  NEXT_PUBLIC_LOGIN_URL: ""

service:
  type: ClusterIP
  port: 80

httpRoute:
  enabled: false
  hostnames:
    - beep.example.com
  parentRefs:
    - name: default-gateway
      namespace: ""
      sectionName: ""

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

serviceAccount:
  create: false
  name: ""
  annotations: {}

podAnnotations: {}
podSecurityContext: {}
securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  readOnlyRootFilesystem: false

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 3
  periodSeconds: 5
