{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "beep-website.fullname" . }}
  labels:
    {{- include "beep-website.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- range .Values.httpRoute.parentRefs }}
    - name: {{ .name }}
      {{- if .namespace }}
      namespace: {{ .namespace }}
      {{- end }}
      {{- if .sectionName }}
      sectionName: {{ .sectionName }}
      {{- end }}
    {{- end }}
  {{- if .Values.httpRoute.hostnames }}
  hostnames:
    {{- range .Values.httpRoute.hostnames }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: Exact
            value: /
      backendRefs:
        - name: {{ include "beep-website.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
